//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_GFX_Censor_H
#define METASPRITE_GFX_Censor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define GFX_Censor_TILE_ORIGIN 0
#define GFX_Censor_TILE_W 8
#define GFX_Censor_TILE_H 8
#define GFX_Censor_WIDTH 40
#define GFX_Censor_HEIGHT 8
#define GFX_Censor_TILE_COUNT 5
#define GFX_Censor_PALETTE_COUNT 1
#define GFX_Censor_COLORS_PER_PALETTE 4
#define GFX_Censor_TOTAL_COLORS 4
#define GFX_Censor_MAP_ATTRIBUTES 0

BANKREF_EXTERN(GFX_Censor)

extern const palette_color_t GFX_Censor_palettes[4];
extern const uint8_t GFX_Censor_tiles[80];

extern const unsigned char GFX_Censor_map[5];

#endif
