/*

 MAP_LEVEL0.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 24 x 24
   Tile set      : C:\gbdk\projects\jasper_demo\GFX_Level0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 45
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level0Width 24
#define Level0Height 24
#define Level0Bank 0

extern unsigned char Level0[];

/* End of MAP_LEVEL0.H */
