/*

 MAP_HUD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\projects\jasper_demo\GFX_HUD.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map_HUDWidth 20
#define Map_HUDHeight 18
#define Map_HUDBank 0

extern unsigned char Map_HUD[];

/* End of MAP_HUD.H */
