//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Screen_Title_H
#define METASPRITE_Screen_Title_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Screen_Title_TILE_ORIGIN 0
#define Screen_Title_TILE_W 8
#define Screen_Title_TILE_H 8
#define Screen_Title_WIDTH 160
#define Screen_Title_HEIGHT 152
#define Screen_Title_TILE_COUNT 124
#define Screen_Title_PALETTE_COUNT 1
#define Screen_Title_COLORS_PER_PALETTE 4
#define Screen_Title_TOTAL_COLORS 4
#define Screen_Title_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Screen_Title)

extern const palette_color_t Screen_Title_palettes[4];
extern const uint8_t Screen_Title_tiles[1984];

extern const unsigned char Screen_Title_map[380];

#endif
