//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Screen_GameOver_H
#define METASPRITE_Screen_GameOver_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Screen_GameOver_TILE_ORIGIN 0
#define Screen_GameOver_TILE_W 8
#define Screen_GameOver_TILE_H 8
#define Screen_GameOver_WIDTH 160
#define Screen_GameOver_HEIGHT 152
#define Screen_GameOver_TILE_COUNT 116
#define Screen_GameOver_PALETTE_COUNT 1
#define Screen_GameOver_COLORS_PER_PALETTE 4
#define Screen_GameOver_TOTAL_COLORS 4
#define Screen_GameOver_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Screen_GameOver)

extern const palette_color_t Screen_GameOver_palettes[4];
extern const uint8_t Screen_GameOver_tiles[1856];

extern const unsigned char Screen_GameOver_map[380];

#endif
