//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Screen_Intro_H
#define METASPRITE_Screen_Intro_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Screen_Intro_TILE_ORIGIN 0
#define Screen_Intro_TILE_W 8
#define Screen_Intro_TILE_H 8
#define Screen_Intro_WIDTH 160
#define Screen_Intro_HEIGHT 144
#define Screen_Intro_TILE_COUNT 27
#define Screen_Intro_PALETTE_COUNT 1
#define Screen_Intro_COLORS_PER_PALETTE 4
#define Screen_Intro_TOTAL_COLORS 4
#define Screen_Intro_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Screen_Intro)

extern const palette_color_t Screen_Intro_palettes[4];
extern const uint8_t Screen_Intro_tiles[432];

extern const unsigned char Screen_Intro_map[360];

#endif
