//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Sprite_H_H
#define METASPRITE_Sprite_H_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Sprite_H_TILE_ORIGIN 0
#define Sprite_H_TILE_W 8
#define Sprite_H_TILE_H 16
#define Sprite_H_WIDTH 8
#define Sprite_H_HEIGHT 16
#define Sprite_H_TILE_COUNT 40
#define Sprite_H_PALETTE_COUNT 1
#define Sprite_H_COLORS_PER_PALETTE 4
#define Sprite_H_TOTAL_COLORS 4
#define Sprite_H_PIVOT_X 4
#define Sprite_H_PIVOT_Y 4
#define Sprite_H_PIVOT_W 8
#define Sprite_H_PIVOT_H 16

BANKREF_EXTERN(Sprite_H)

extern const palette_color_t Sprite_H_palettes[4];
extern const uint8_t Sprite_H_tiles[640];

extern const metasprite_t* const Sprite_H_metasprites[20];

#endif
