//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Sprite_Jasper_Back_H
#define METASPRITE_Sprite_Jasper_Back_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Sprite_Jasper_Back_TILE_ORIGIN 0
#define Sprite_Jasper_Back_TILE_W 8
#define Sprite_Jasper_Back_TILE_H 8
#define Sprite_Jasper_Back_WIDTH 24
#define Sprite_Jasper_Back_HEIGHT 16
#define Sprite_Jasper_Back_TILE_COUNT 16
#define Sprite_Jasper_Back_PALETTE_COUNT 1
#define Sprite_Jasper_Back_COLORS_PER_PALETTE 4
#define Sprite_Jasper_Back_TOTAL_COLORS 4
#define Sprite_Jasper_Back_PIVOT_X 12
#define Sprite_Jasper_Back_PIVOT_Y 8
#define Sprite_Jasper_Back_PIVOT_W 24
#define Sprite_Jasper_Back_PIVOT_H 16

BANKREF_EXTERN(Sprite_Jasper_Back)

extern const palette_color_t Sprite_Jasper_Back_palettes[4];
extern const uint8_t Sprite_Jasper_Back_tiles[256];

extern const metasprite_t* const Sprite_Jasper_Back_metasprites[4];

#endif
