//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Sprite_Eyes_H
#define METASPRITE_Sprite_Eyes_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Sprite_Eyes_TILE_ORIGIN 0
#define Sprite_Eyes_TILE_W 8
#define Sprite_Eyes_TILE_H 16
#define Sprite_Eyes_WIDTH 8
#define Sprite_Eyes_HEIGHT 16
#define Sprite_Eyes_TILE_COUNT 2
#define Sprite_Eyes_PALETTE_COUNT 1
#define Sprite_Eyes_COLORS_PER_PALETTE 4
#define Sprite_Eyes_TOTAL_COLORS 4
#define Sprite_Eyes_PIVOT_X 0
#define Sprite_Eyes_PIVOT_Y 0
#define Sprite_Eyes_PIVOT_W 8
#define Sprite_Eyes_PIVOT_H 16

BANKREF_EXTERN(Sprite_Eyes)

extern const palette_color_t Sprite_Eyes_palettes[4];
extern const uint8_t Sprite_Eyes_tiles[32];

extern const metasprite_t* const Sprite_Eyes_metasprites[1];

#endif
