//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Sprite_Jasper_H
#define METASPRITE_Sprite_Jasper_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Sprite_Jasper_TILE_ORIGIN 0
#define Sprite_Jasper_TILE_W 8
#define Sprite_Jasper_TILE_H 16
#define Sprite_Jasper_WIDTH 24
#define Sprite_Jasper_HEIGHT 16
#define Sprite_Jasper_TILE_COUNT 60
#define Sprite_Jasper_PALETTE_COUNT 1
#define Sprite_Jasper_COLORS_PER_PALETTE 4
#define Sprite_Jasper_TOTAL_COLORS 4
#define Sprite_Jasper_PIVOT_X 12
#define Sprite_Jasper_PIVOT_Y 8
#define Sprite_Jasper_PIVOT_W 24
#define Sprite_Jasper_PIVOT_H 16

BANKREF_EXTERN(Sprite_Jasper)

extern const palette_color_t Sprite_Jasper_palettes[4];
extern const uint8_t Sprite_Jasper_tiles[960];

extern const metasprite_t* const Sprite_Jasper_metasprites[13];

#endif
