//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(Sprite_Eyes)

const palette_color_t Sprite_Eyes_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(102,182, 50), RGB8( 32,121, 73), RGB8( 13, 65, 87)
	
};

const uint8_t Sprite_Eyes_tiles[32] = {
	0xd5,0xd5,0x55,0x55,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t Sprite_Eyes_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, 0), METASPR_TERM
};

const metasprite_t* const Sprite_Eyes_metasprites[1] = {
	Sprite_Eyes_metasprite0
};
