//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Sprite_Jasper_Side_H
#define METASPRITE_Sprite_Jasper_Side_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Sprite_Jasper_Side_TILE_ORIGIN 0
#define Sprite_Jasper_Side_TILE_W 8
#define Sprite_Jasper_Side_TILE_H 8
#define Sprite_Jasper_Side_WIDTH 24
#define Sprite_Jasper_Side_HEIGHT 16
#define Sprite_Jasper_Side_TILE_COUNT 18
#define Sprite_Jasper_Side_PALETTE_COUNT 1
#define Sprite_Jasper_Side_COLORS_PER_PALETTE 4
#define Sprite_Jasper_Side_TOTAL_COLORS 4
#define Sprite_Jasper_Side_PIVOT_X 12
#define Sprite_Jasper_Side_PIVOT_Y 8
#define Sprite_Jasper_Side_PIVOT_W 24
#define Sprite_Jasper_Side_PIVOT_H 16

BANKREF_EXTERN(Sprite_Jasper_Side)

extern const palette_color_t Sprite_Jasper_Side_palettes[4];
extern const uint8_t Sprite_Jasper_Side_tiles[288];

extern const metasprite_t* const Sprite_Jasper_Side_metasprites[4];

#endif
